media:
  - name: images
    label: Images
    input: assets/images
    output: /assets/images
    categories: [image]
    rename: safe

content:
  - name: posts
    label: Posts
    type: collection
    path: content/posts
    filename: "{primary}.md"
    view:
      fields: [title, category, date, published]
      primary: title
      sort: date
      default:
        sort: date
        order: desc
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: date
        label: Date
        type: date
        required: true
      - name: category
        label: Section
        type: select
        required: true
        options:
          values:
            - Books
            - Poetry
            - TV
            - People
            - My Writing
            - Memes
      - name: cover
        label: Cover image
        type: image
        options:
          media: images
          path: assets/images
      - name: excerpt
        label: Short description
        type: text
      - name: published
        label: Published
        type: boolean
      - name: body
        label: Article
        type: rich-text
        options:
          media: images
          path: assets/images
          switcher: true
